### PR TITLE
Update timeline-track-stacked-base.mjs DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @victorgomes Could You Please Review This PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @victorgomes Could You Please Review This PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @pthier Could You Please Review This PR 
Thanks

**Comment by pthier** [comment]
Hi, this is the wrong repo for this change.
This should be done directly in the v8 repository (not the node clone). See https://v8.dev/docs/contribute

**Comment by Shivam7-1** [comment]
Hi @pthier Thanks For Replying 
So Should I Close this PR Overhere ?

Because as I Don't see this File name in V8 Repo 
Thanks

**Comment by pthier** [comment]
Yes, let's close this PR.
The file is in tools/system-analyzer/... in the v8 checkout.

Besides that, I don't think the change makes a lot of sense. The line you are changing only clears the value. There is no user-controlled input involved.

**Comment by Shivam7-1** [comment]
Hi @pthier  Thanks For Response  Could You Please Help me out I am facing error while while creating PR in V8 Repo 
whenever i try to push chnages i am geeting this error 
`remote: INVALID_ARGUMENT: Request contains an invalid argument
remote: [type.googleapis.com/google.rpc.LocalizedMessage]
remote: locale: "en-US"
remote: message: "Invalid authentication credentials. Please generate a new identifier: https://chromium.googlesource.com/new-password"
remote:
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "ece278af4330446a8e9668e0c0b225e3"
fatal: unable to access 'https://chromium.googlesource.com/v8/v8.git/': The requested URL returned error: 400
`

i had also visted to https://chromium.googlesource.com/new-password for password changes i had added to all mentioned things to this file  `.gitcookies`  but still geeting above error Could You Please Help me How can i resolve this Problem
Thanks

**Pull request closed without merging**
