### PR TITLE
test: remove unnecessary V8 flag

### PR DESCRIPTION
**Pull request by aduh95**
Refs: https://github.com/nodejs/node/pull/37671
Refs: https://chromium-review.googlesource.com/c/v8/v8/+/2741582

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by syg** [comment]
@victorgomes PTAL so @aduh95 can land the upstream CL.

**Comment by aduh95** [comment]
Should I rebase that on top of https://github.com/v8/node/tree/node-ci-2021-03-09?

**Comment by syg** [comment]
> Should I rebase that on top of https://github.com/v8/node/tree/node-ci-2021-03-09?

Yeah, I think it should always be based on top of the most recent ci branch.

**Comment by aduh95** [comment]
This was already merged on `node-ci-2021-04-06` branch.

**Pull request closed without merging**
