### PR TITLE
inspector: bring in inspector_protocol as a direct dependency

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch adds
[inspector_protocol](https://www.google.com/url?q=https://chromium.googlesource.com/deps/inspector_protocol/)
as a direct dependency to node.js. Inspector Protocol is used in node.js
tracing, and this is required to be able to roll protocol independently
from v8.

This is necessary to roll protocol to v8: [v8 patch](https://chromium-review.googlesource.com/c/v8/v8/+/1149321)

inspector_protocol dependency comes with two more libs:
- jinja2
- markupsafe

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by aslushnikov** [comment]
@hashseed can you please take a look?

**Comment by hashseed** [comment]
Can I get some more context? Is the copy of inspector protocol in V8 still required when rolling into V8, e.g. when running `v8/tools/node/update_node.py`? If yes, please provide a change to that script too. We use it continuous integration. And, do you intend to upstream this change to Node.js?

**Comment by hashseed** [comment]
I see. That means that we no longer have to copy inspector when running `v8/tools/node/update_node.py`, right? And this will be upstreamed?

**Comment by ak239** [comment]
I am not sure that I understand what inspector did you mention. I believe we still need both one inside V8 and one inside node. One from V8 is used by inspector inside V8, one from node is used by node inspector_agent.cc.
Yes, it will be upstreamed. Should we create upstream PR?

**Comment by hashseed** [comment]
I see. So we are not sharing the code between Node and V8, right?

Upstream PR would be great, yes. Once that lands I can just sync with upstream.

**Comment by refack** [comment]
I think this can be closed?

**Pull request closed without merging**
