### PR TITLE
Fix ninja build on Windows & --build-v8-with-gn improvements

### PR DESCRIPTION
**Pull request by agrieve**

### CODE REVIEW

**Comment by hashseed** [comment]
The build instructions are

```
  set CC="%cd%\deps\v8\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe"
  python configure --build-v8-with-gn
```

However, clang-cl.exe is checked out via gclient hooks during `configure` in the first place, so that part seems a bit unpolished. Is there any way to hide this detail inside of `configure`?

**Comment by agrieve** [comment]
The build also works with msvc, so we wouldn't want to set it unconditionally. Maybe add a `--use-clang-cl` flag?

**Comment by hashseed** [comment]
Yup that makes sense.

**Comment by agrieve** [comment]
Split this into https://github.com/v8/node/pull/60 https://github.com/v8/node/pull/58

**Pull request closed without merging**
