### PR TITLE
No longer use deprecated version of v8::Object::SetAccessor

### PR DESCRIPTION
**Pull request by hashseed**

### CODE REVIEW

**Comment by addaleax** [comment]
@hashseed These kinds of things can always be PR’ed against the main repo as well, if you want :)

**Comment by hashseed** [comment]
@addaleax I know. I'm just trying to optimize for turn-around time for [my V8 CL](https://chromium-review.googlesource.com/c/v8/v8/+/848782) :)

I'll submit a PR to upstream soon.

**Comment by fhinkel** [comment]
Late LGTM :) Pinging @targos who's usually doing the V8 updates: How much extra work do commit like this cause? Is it OK to have them or should we PR's them against the main repo and wait longer until we can land something in V8?

**Comment by hashseed** [comment]
Turns out it's already been [fixed upstream](https://github.com/nodejs/node/pull/16958). And @addaleax actually reviewed it :stuck_out_tongue_winking_eye:

**Comment by targos** [comment]
@fhinkel you mean commits like in this PR or https://chromium-review.googlesource.com/c/v8/v8/+/848782 ?

**Comment by fhinkel** [comment]
I mean a PR like this to v8/node instead of to node/node. I thought when you update V8 in Node master, you cherry-pick from v8/node.

**Comment by fhinkel** [comment]
> Turns out it's already been fixed upstream. And @addaleax actually reviewed it 😜

And I landed it. I thought it looked familiar 😊

**Comment by targos** [comment]
v8/node is not part of my usual workflow. I sometimes look at it if canary has failures to see if it's fixed here.

**Comment by fhinkel** [comment]
Thanks for clarifying, makes sense.

**Pull request merged**
