### PR TITLE
update to nodejs/canary

### PR DESCRIPTION
**Pull request by targos**
This is with V8 lkgr at https://github.com/v8/v8/commit/e7f8575851a0a56ffe6772d98fd8d90602e6876b

Tests all pass locally

### CODE REVIEW

**Comment by fhinkel** [comment]
Rubberstamp lgtm. Thanks for putting this together!

**Comment by fhinkel** [comment]
How hard is it to rebase this?

**Comment by targos** [comment]
I'll try to rebase

**Comment by targos** [comment]
actually I'm not sure what you meant. Rebase this branch on nodejs/master or rebase my fork so that this PR has no conflict?

**Comment by targos** [comment]
ATM this is node master + V8 upgrade + floating patches

**Comment by targos** [comment]
By looking at the history, it seems that this branch is usually force-pushed to upgrade V8

**Comment by fhinkel** [comment]
I meant fix the conflicts so we can merge onto v8/node/vee-eight-lkgr. I thought the conflict came from our last commit (~5 minutes ago). But then it wouldn't be so many affected files. :thinking: Did it have conflicts when you first opened the PR?

**Comment by fhinkel** [comment]
Oh, never mind then. I thought it was related this last change.

**Comment by targos** [comment]
I cherry-picked https://github.com/v8/node/pull/10/commits/d4bd50aa35d4bb5031b1d00df4e53cba818b3397 and https://github.com/v8/node/pull/10/commits/53ebc43a6fd8fa394c7127f1dbfb65b7a4186371.

Unless there are additional commits deep in the history, I think everything is here.

**Comment by fhinkel** [comment]
OK. Waiting for @ofrobots to have a look, too.

**Comment by ofrobots** [comment]
Rubberstamp LGTM. Thanks for putting this together.

@fhinkel - I'll let you force push this, given that the V8 team is currently working on making I+TF stick and might be sensitive to 'change'.

**Comment by fhinkel** [comment]
I force pushed your canary branch. Let's see what happens :see_no_evil:

**Pull request merged**
